version: '3.4'

services:
  conferenceplanner.backend:
    image: ${DOCKER_REGISTRY-}conferenceplannerbackend
    build:
      context: .
      dockerfile: ConferencePlanner.Backend/Dockerfile
    depends_on:
      - db

  conferenceplanner.frontend:
    image: ${DOCKER_REGISTRY-}conferenceplannerfrontend
    build:
      context: .
      dockerfile: ConferencePlanner.FrontEnd/Dockerfile
    links:
      - conferenceplanner.backend

  db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "ConferencePlanner1234$$"
      ACCEPT_EULA: "Y"